// --- GLOBALS ---
const GAS_WEB_APP_URL = "https://script.google.com/macros/s/AKfycbyNh_IDSpgQEGL12PJQ56Mc5VW8a8WWXGuzuWMuNPpmPVMLFYpWsApdbR3iOk56LWVf/exec";

const state = { masterItemDatabase: [], currentUser: null, autocompleteDebounceTimer: null, notificationInterval: null, lastNotificationCheck: new Date().toISOString(), requestList: [], requests: [], lastUsedUnitCount: 1, lastUsedDiscount: 0, lastUsedVat: 0 };
const dom = {};

// --- API & AUTH ---
async function apiRequest(action, data = {}, showLoader = false) { if (showLoader) dom.loadingIndicator.style.display = 'flex'; try { const payload = { action, user: state.currentUser, data }; const response = await fetch(GAS_WEB_APP_URL, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(`Network error: ${response.statusText}`); const result = await response.json(); if (!result.success) throw new Error(result.error || `API error for action: ${action}`); return result; } catch (error) { console.error(`API Error (${action}):`, error); displayMessage(error.message, true); return { success: false, error: error.message }; } finally { if (showLoader) dom.loadingIndicator.style.display = 'none'; } }
async function handleLogin(event) { if (event) event.preventDefault(); const loginCode = dom.loginCodeInput.value.trim(); if (!loginCode) { showLoginError("Login Code is required."); return; } dom.loginError.style.display = 'none'; const loginResult = await apiRequest('login', { loginCode: loginCode }, true); if (!loginResult.success) { showLoginError(loginResult.error || "Login failed."); return; } state.currentUser = loginResult.user; const dbResult = await apiRequest('getItemDatabase', {}, true); if (dbResult.success) { state.masterItemDatabase = dbResult.data; sessionStorage.setItem('currentUser', JSON.stringify(state.currentUser)); initializeApp(); } else { showLoginError("Could not load product database. Please try again."); state.currentUser = null; } }
async function initializeApp() { showView('main-view'); dom.welcomeMessage.textContent = `Welcome, ${state.currentUser.DisplayName} (${state.currentUser.Role})`; startNotificationPolling(); if (state.currentUser.Role === 'Branch') { dom.branchContent.style.display = 'block'; dom.officerContent.style.display = 'none'; await loadAndRenderRequests(true); } else if (state.currentUser.Role === 'Officer') { dom.branchContent.style.display = 'none'; dom.officerContent.style.display = 'block'; await loadAndRenderRequests(true); } }
function handleLogout() { state.currentUser = null; sessionStorage.removeItem('currentUser'); if (state.notificationInterval) clearInterval(state.notificationInterval); showView('login-view'); dom.loginForm.reset(); state.requests = []; state.requestList = []; state.masterItemDatabase = []; }

// --- DATA LOADING & RENDERING ---
async function loadAndRenderRequests(showLoader = false) { const result = await apiRequest('getRequests', {}, showLoader); if (result.success) { state.requests = result.data; renderRequests(); flashTable(state.currentUser.Role === 'Officer' ? 'officer-requests-table' : 'branch-requests-table'); } }
function renderRequests() { if (!state.currentUser) return; if (state.currentUser.Role === 'Officer') { renderOfficerRequests(state.requests); } else if (state.currentUser.Role === 'Branch') { renderBranchRequests(state.requests); } }
function renderBranchRequests(requests) {
    const tbody = dom.branchRequestsTable.querySelector('tbody');
    if (!requests || requests.length === 0) { tbody.innerHTML = '<tr><td colspan="3" class="text-center p-4">No submission history found.</td></tr>'; return; }
    tbody.innerHTML = requests.map(r => {
        const { badgeClass, statusText } = getStatusSummary(r);
        return `<tr data-request-id="${r.RequestID}" style="cursor: pointer;"><td>${r.RequestID}</td><td>${new Date(r.SubmissionTimestamp).toLocaleDateString()}</td><td><span class="badge ${badgeClass}">${statusText}</span></td></tr>`;
    }).join('');
}
function renderOfficerRequests(requests) {
    const tbody = dom.officerRequestsTable.querySelector('tbody');
    if (!requests || requests.length === 0) { tbody.innerHTML = '<tr><td colspan="6" class="text-center p-4">No requests found.</td></tr>'; return; }
    tbody.innerHTML = requests.map(r => {
        const { badgeClass, statusText } = getStatusSummary(r);
        const isCompleted = r.itemsPending === 0;
        return `<tr class="${isCompleted ? 'table-light text-muted' : ''}"><td>${r.RequestID}</td><td>${new Date(r.SubmissionTimestamp).toLocaleDateString()}</td><td>${r.Branch}</td><td>${r.SubmittedBy}</td><td><span class="badge ${badgeClass}">${statusText}</span></td><td><button class="btn btn-sm btn-primary review-btn" data-request-id="${r.RequestID}"><i class="fas fa-search"></i> ${isCompleted ? 'View' : 'Review'}</button></td></tr>`;
    }).join('');
}

// --- BRANCH USER FORM & LIST LOGIC ---
function handleCodeInput() { clearTimeout(state.autocompleteDebounceTimer); state.autocompleteDebounceTimer = setTimeout(() => { const term = dom.codeInput.value.trim().toLowerCase(); getItemDetails(); if (term.length < 1) { dom.suggestionsBox.style.display = 'none'; return; } const suggestions = state.masterItemDatabase.filter(item => String(item.code).toLowerCase().includes(term) || String(item.name).toLowerCase().includes(term)).slice(0, 10); if (suggestions.length > 0) { dom.suggestionsBox.innerHTML = suggestions.map(s => `<div class="autocomplete-item" data-code="${s.code}"><strong>${s.code}</strong> - ${s.name}</div>`).join(''); dom.suggestionsBox.style.display = 'block'; } else { dom.suggestionsBox.style.display = 'none'; } }, 250); }
function selectAutocompleteItem(code) { dom.codeInput.value = code; dom.suggestionsBox.style.display = 'none'; getItemDetails(); dom.unitPriceInput.focus(); }
function getItemDetails() { const code = dom.codeInput.value.trim(); dom.nameInput.value = ''; dom.supplierNameInput.value = ''; if (!code) return; const foundItem = state.masterItemDatabase.find(item => String(item.code) === code); if (foundItem) { dom.nameInput.value = foundItem.name || ''; dom.supplierNameInput.value = foundItem['supplier name'] || ''; } }
function toggleAlternateSupplier() { dom.alternateSupplierDiv.style.display = dom.alternateSupplierCheck.checked ? 'block' : 'none'; }
function toggleCurrentPriceField() { dom.currentPriceDiv.style.display = dom.typeSelect.value === 'مرتجع' ? 'block' : 'none'; }
function openCalculatorModal() { dom.modalCost.value = ''; dom.modalUnit.value = state.lastUsedUnitCount || '1'; dom.modalDiscount.value = state.lastUsedDiscount || '0'; dom.modalVat.value = state.lastUsedVat || '0'; calculateInModal(); $('#calculatorModal').modal('show'); }
function calculateInModal() { const cost = parseFloat(dom.modalCost.value) || 0; const unit = parseInt(dom.modalUnit.value) || 1; const discount = parseFloat(dom.modalDiscount.value) || 0; const vatRate = parseFloat(dom.modalVat.value) || 0; const discountedCost = cost * (1 - discount / 100); const finalCasePrice = discountedCost * (1 + vatRate / 100); const finalUnitPrice = (unit > 0) ? (finalCasePrice / unit) : 0; dom.modalUnitPriceResult.value = finalUnitPrice.toFixed(3); dom.modalCasePriceResult.value = finalCasePrice.toFixed(3); }
function applyCalculatorPrice() { dom.unitPriceInput.value = dom.modalUnitPriceResult.value; state.lastUsedUnitCount = parseInt(dom.modalUnit.value) || 1; state.lastUsedDiscount = parseFloat(dom.modalDiscount.value) || 0; state.lastUsedVat = parseFloat(dom.modalVat.value) || 0; $('#calculatorModal').modal('hide'); }
function addToList() { const code = dom.codeInput.value.trim(); const unitPrice = dom.unitPriceInput.value; if (!code || !unitPrice) { displayMessage("Code and Final Unit Price are required.", true); return; } const alternateSupplierCheck = dom.alternateSupplierCheck.checked; const alternateSupplierName = dom.alternateSupplierNameInput.value.trim(); let supplier = dom.supplierNameInput.value.trim(); if(alternateSupplierCheck && alternateSupplierName) supplier = alternateSupplierName; const finalUnitPrice = parseFloat(unitPrice); const newItem = { code: code, name: dom.nameInput.value.trim(), supplier: supplier, units: state.lastUsedUnitCount, discount: state.lastUsedDiscount, vat: state.lastUsedVat, piece: finalUnitPrice.toFixed(3), case: (finalUnitPrice * state.lastUsedUnitCount).toFixed(3), type: dom.typeSelect.value, current: dom.currentPriceInput.value || '0' }; state.requestList.push(newItem); displayMessage("Item added to list.", false, 1500); clearRequestForm(); renderRequestListTable(); }
function renderRequestListTable() { const card = dom.submissionListCard; const tbody = dom.submissionListTbody; const header = card.querySelector('.card-header'); if (state.requestList.length === 0) { card.style.display = 'none'; return; } card.style.display = 'block'; header.textContent = `Pending Request Items (${state.requestList.length})`; tbody.innerHTML = state.requestList.map((item, index) => `<tr><td>${item.code}</td><td>${item.name}</td><td>${item.supplier}</td><td>${item.units}</td><td>${item.discount}%</td><td>${item.vat}%</td><td>${item.piece}</td><td>${item.case}</td><td><button class="btn btn-danger btn-sm remove-item-btn" data-index="${index}" title="Remove"><i class="fas fa-times"></i></button></td></tr>`).join(''); }
function removeFromList(index) { state.requestList.splice(index, 1); renderRequestListTable(); }
function clearRequestList() { if (confirm("Are you sure you want to clear the entire pending list?")) { state.requestList = []; renderRequestListTable(); } }
async function submitAllRequests() { if (state.requestList.length === 0) { displayMessage("List is empty.", true); return; } if (!confirm(`Submit ${state.requestList.length} item(s) for approval?`)) return; const result = await apiRequest('submitRequest', state.requestList, true); if (result.success) { displayMessage(result.message || 'Requests submitted!'); state.requestList = []; renderRequestListTable(); await loadAndRenderRequests(); } }
function clearRequestForm() { dom.itemDetailsForm.reset(); toggleAlternateSupplier(); toggleCurrentPriceField(); dom.codeInput.focus(); }
async function viewRequestDetails(requestID) { const result = await apiRequest('getRequestDetails', { requestID }, true); if (result.success && result.data) { dom.branchModalRequestId.textContent = requestID; const tbody = dom.branchModalItemsTbody; tbody.innerHTML = result.data.map(item => `<tr><td>${item.ItemCode}</td><td>${item.ItemName}</td><td>${item.SubmittedSupplier}</td><td>${item.SubmittedPiecePrice}</td><td><span class="badge ${getStatusClass(item.Status)}">${item.Status}</span></td></tr>`).join(''); $('#branch-view-details-modal').modal('show'); } }

// --- OFFICER LOGIC ---
async function reviewRequest(requestID) { const result = await apiRequest('getRequestDetails', { requestID }, true); if (result.success && result.data) { dom.modalRequestIdTitle.textContent = requestID; $('#request-details-modal').data('requestId', requestID); renderOfficerModal(result.data); $('#request-details-modal').modal('show'); } }
function renderOfficerModal(items) { const tbody = dom.modalItemsTbody; tbody.innerHTML = items.map(item => `<tr data-item-id="${item.ItemID}"><td>${item.ItemCode}</td><td>${item.ItemName}</td><td>${item.SubmittedPiecePrice}</td><td>${item.SubmittedCasePrice}</td><td><select class="form-control form-control-sm item-status-select"><option ${item.Status === 'Pending' ? 'selected' : ''}>Pending</option><option ${item.Status === 'تم التعديل' ? 'selected' : ''}>تم التعديل</option><option ${item.Status === 'غير مسموع بالتعديل ويتم رفع الصنف' ? 'selected' : ''}>غير مسموع بالتعديل ويتم رفع الصنف</option><option ${item.Status === 'تم التعديل جزئيا' ? 'selected' : ''}>تم التعديل جزئيا</option><option ${item.Status === 'يرجي مراجعة كود الاستثناء' ? 'selected' : ''}>يرجي مراجعة كود الاستثناء</option><option ${item.Status === 'يتم المراجعة مع المورد' ? 'selected' : ''}>يتم المراجعة مع المورد</option></select></td></tr>`).join(''); }
function applyMasterStatus() { const masterStatus = dom.masterStatusSelect.value; if (!masterStatus) return; dom.modalItemsTbody.querySelectorAll('.item-status-select').forEach(select => { select.value = masterStatus; }); }
async function saveItemChanges() { const requestID = $('#request-details-modal').data('requestId'); const updates = Array.from(dom.modalItemsTbody.querySelectorAll('tr')).map(row => ({ itemID: row.dataset.itemId, newStatus: row.querySelector('.item-status-select').value })); if (updates.length === 0) { displayMessage("No items to update.", true); return; } const result = await apiRequest('updateItemStatuses', { updates: updates, requestID: requestID }, true); if (result.success) { displayMessage(result.message || 'Item changes saved!'); $('#request-details-modal').modal('hide'); await loadAndRenderRequests(); } }

// --- UTILITIES & STARTUP ---
function getStatusSummary(request) { if (request.itemsPending === 0) { return { badgeClass: 'badge-success', statusText: `✅ Processed (${request.itemsTotal})` }; } return { badgeClass: 'badge-info', statusText: `⚠️ ${request.itemsPending} / ${request.itemsTotal} Pending` }; }
function getStatusClass(status) { if (status === 'Pending') return 'badge-secondary'; if (status.includes('مراجعة') || status.includes('مسموع')) return 'badge-warning'; return 'badge-primary'; }
function exportModalAsJPG(elementId, baseFileName) { const elementToCapture = document.getElementById(elementId); const requestId = $('#' + (elementId.includes('officer') ? 'request-details-modal' : 'branch-view-details-modal')).find('.modal-title span').text(); const fileName = `${baseFileName}_${requestId || 'export'}.jpg`; displayMessage("Exporting image...", false, 2000); html2canvas(elementToCapture, { scale: 1.5, useCORS: true, backgroundColor: '#ffffff' }).then(canvas => { const link = document.createElement('a'); link.href = canvas.toDataURL("image/jpeg", 0.9); link.download = fileName; document.body.appendChild(link); link.click(); document.body.removeChild(link); }).catch(err => { console.error("Image export failed:", err); displayMessage("Image export failed.", true); }); }
function startNotificationPolling() { if (state.notificationInterval) clearInterval(state.notificationInterval); state.notificationInterval = setInterval(async () => { if (document.hidden || !state.currentUser) return; const result = await apiRequest('checkForNotifications', { lastCheck: state.lastNotificationCheck }); if (result.success) { state.lastNotificationCheck = new Date().toISOString(); if (result.data.newEvents.length > 0) { displayMessage(result.data.newEvents.join('\n'), false, 10000); dom.notificationSound.play().catch(e => console.warn("Audio playback failed.", e)); await loadAndRenderRequests(); } } }, 15000); }
function flashTable(tableId) { const table = document.getElementById(tableId); if (!table) return; table.classList.add('table-flash'); setTimeout(() => { table.classList.remove('table-flash'); }, 1500); }
function showView(viewId) { document.querySelectorAll('.view').forEach(v => v.style.display = 'none'); document.getElementById(viewId).style.display = 'block'; }
function displayMessage(message, isError = false, duration = 4000) { const toastContainer = dom.toastContainer; const toastId = 'toast-' + Date.now(); const toastBG = isError ? 'bg-danger' : 'bg-success'; const toastHTML = `<div id="${toastId}" class="toast show ${toastBG} text-white" role="alert" aria-live="assertive" aria-atomic="true"><div class="toast-body d-flex justify-content-between"><span>${message}</span><button type="button" class="ml-2 mb-1 close text-white" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button></div></div>`; toastContainer.insertAdjacentHTML('beforeend', toastHTML); const toastElement = document.getElementById(toastId); $(toastElement).toast({ delay: duration, autohide: true }); $(toastElement).on('hidden.bs.toast', function () { this.remove(); }); }
function showLoginError(message) { dom.loginError.textContent = message; dom.loginError.style.display = 'block'; }
function cacheDOMElements() { dom.loginView = document.getElementById('login-view'); dom.mainView = document.getElementById('main-view'); dom.loginForm = document.getElementById('login-form'); dom.loginCodeInput = document.getElementById('loginCode'); dom.loginError = document.getElementById('login-error'); dom.loadingIndicator = document.getElementById('loading-indicator'); dom.welcomeMessage = document.getElementById('welcome-message'); dom.logoutBtn = document.getElementById('logout-btn'); dom.toastContainer = document.getElementById('toast-container'); dom.notificationSound = document.getElementById('notification-sound'); dom.branchContent = document.getElementById('branch-user-content'); dom.itemDetailsForm = document.getElementById('item-details-form'); dom.codeInput = document.getElementById('code'); dom.suggestionsBox = document.getElementById('autocomplete-suggestions'); dom.typeSelect = document.getElementById('type'); dom.currentPriceDiv = document.getElementById('currentPriceDiv'); dom.currentPriceInput = document.getElementById('currentPrice'); dom.nameInput = document.getElementById('name'); dom.supplierNameInput = document.getElementById('supplierName'); dom.alternateSupplierCheck = document.getElementById('alternateSupplierCheck'); dom.alternateSupplierDiv = document.getElementById('alternateSupplierDiv'); dom.alternateSupplierNameInput = document.getElementById('alternateSupplierName'); dom.unitPriceInput = document.getElementById('unitPrice'); dom.calcButton = document.getElementById('calc-btn'); dom.addToListBtn = document.getElementById('add-to-list-btn'); dom.submissionListCard = document.getElementById('submission-list-card'); dom.submissionListTbody = document.getElementById('submission-list-tbody'); dom.branchRequestsTable = document.getElementById('branch-requests-table'); dom.officerContent = document.getElementById('officer-content'); dom.officerRequestsTable = document.getElementById('officer-requests-table'); dom.branchModalRequestId = document.getElementById('branch-modal-request-id'); dom.branchModalItemsTbody = document.getElementById('branch-modal-items-tbody'); dom.modalRequestIdTitle = document.getElementById('modal-request-id-title'); dom.modalItemsTbody = document.getElementById('modal-items-tbody'); dom.masterStatusSelect = document.getElementById('master-status-select'); dom.saveItemChangesBtn = document.getElementById('save-item-changes-btn'); dom.modalCost = document.getElementById('modalCost'); dom.modalUnit = document.getElementById('modalUnit'); dom.modalDiscount = document.getElementById('modalDiscount'); dom.modalVat = document.getElementById('modalVat'); dom.modalUnitPriceResult = document.getElementById('modalUnitPriceResult'); dom.modalCasePriceResult = document.getElementById('modalCasePriceResult'); dom.applyCalcPriceBtn = document.getElementById('apply-calc-price-btn'); }
function setupEventListeners() { dom.loginForm.addEventListener('submit', handleLogin); dom.logoutBtn.addEventListener('click', handleLogout); dom.codeInput.addEventListener('input', handleCodeInput); dom.typeSelect.addEventListener('change', toggleCurrentPriceField); dom.alternateSupplierCheck.addEventListener('change', toggleAlternateSupplier); dom.calcButton.addEventListener('click', openCalculatorModal); dom.addToListBtn.addEventListener('click', addToList); dom.suggestionsBox.addEventListener('click', e => { const item = e.target.closest('.autocomplete-item'); if (item) { selectAutocompleteItem(item.dataset.code); } }); dom.submissionListCard.addEventListener('click', e => { if (e.target.closest('#clear-list-btn')) clearRequestList(); if (e.target.closest('#submit-all-btn')) submitAllRequests(); if (e.target.closest('.remove-item-btn')) removeFromList(e.target.closest('.remove-item-btn').dataset.index); }); dom.branchRequestsTable.addEventListener('click', e => { const row = e.target.closest('tr[data-request-id]'); if (row) viewRequestDetails(row.dataset.requestId); }); dom.officerRequestsTable.addEventListener('click', e => { const btn = e.target.closest('.review-btn'); if (btn) reviewRequest(btn.dataset.requestId); }); dom.masterStatusSelect.addEventListener('change', applyMasterStatus); dom.saveItemChangesBtn.addEventListener('click', saveItemChanges); dom.modalCost.addEventListener('input', calculateInModal); dom.modalUnit.addEventListener('input', calculateInModal); dom.modalDiscount.addEventListener('input', calculateInModal); dom.modalVat.addEventListener('input', calculateInModal); dom.applyCalcPriceBtn.addEventListener('click', applyCalculatorPrice); document.getElementById('export-officer-btn').addEventListener('click', () => exportModalAsJPG('officer-modal-body-exportable', 'request-details')); document.getElementById('export-branch-btn').addEventListener('click', () => exportModalAsJPG('branch-modal-body-exportable', 'request-history')); document.addEventListener('click', (event) => { if (dom.itemDetailsForm && !dom.itemDetailsForm.contains(event.target)) { dom.suggestionsBox.style.display = 'none'; } }); }
document.addEventListener('DOMContentLoaded', function() { cacheDOMElements(); setupEventListeners(); const storedUser = sessionStorage.getItem('currentUser'); if (storedUser) { state.currentUser = JSON.parse(storedUser); const loginCode = state.currentUser.LoginCode; dom.loginCodeInput.value = loginCode; handleLogin(); } else { showView('login-view'); } });
